version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.11.3

commands:
  prepare:
    steps:
      - checkout
      - run: ls modules/*/package.json | xargs -n1 md5sum > deps.txt
      - run: sudo npm i -g npm@6.13.4
      - run:
          # https://yarnpkg.com/en/docs/install#alternatives-stable
          name: Install Yarn@1.21.1
          command: |
            sudo unlink $(which yarn)
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
            echo "export PATH=$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH" >> $BASH_ENV
      - run:
          name: Display version of Node.js, npm and Yarn
          command: |
            node -v
            npm -v
            yarn --version

jobs:
  test:
    executor:
      name: default
    steps:
      - prepare
      - run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          npm whoami
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ .Branch }}-{{ checksum "deps.txt" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
            - modules/format/node_modules
            - modules/retriever/node_modules
            - modules/updater/node_modules
          key: v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ .Branch }}-{{ checksum "deps.txt" }}
      - run: yarn bootstrap
      - run: yarn build
      - run: yarn cov-test
      - run: npx lcov-result-merger 'modules/*/coverage/lcov.info' | npx coveralls
  deploy:
    executor:
      name: default
    steps:
      - prepare
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ .Branch }}-{{ checksum "deps.txt" }}
      - run:
          name: Clean tmp files
          command: yarn clean-tmp
      - run:
          name: Build packages
          command: yarn build
      - run:
          name: Publish packages
          command: echo "To be implemented"

workflows:
  version: 2.1
  test_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - /^(release)\/.*/
